export const USER_INFO = 'USER_INFO'
export const ADD_TODO = 'ADD_TODO'
export const GET_ALL_TODO = 'GET_ALL_TODO'
export const GET_COMPLETED_TODO = 'GET_COMPLETED_TODO'
export const GET_UNCOMPLETED_TODO = 'GET_UNCOMPLETED_TODO'
export const DEL_TODO = 'DEL_TODO'
